### ISSUE TITLE
cvm_slicer.py issues with plotting for volumes without "depth" variable

### ISSUE THREAD

**Issue by jrdelph** [cascadiaquakes/CRESCENT-CVM#8]
Ran in to two issues using cvm_slicer.py on a phase velocity volume (latitude longitude period velocity). Note that there is no "depth" portion to this volume:

1) If you are working on a "period" (not depth) volume, the "xsection" choice in "subset" fails because it explicitly looks for the "depth" variable
![Screenshot 2024-11-27 at 7 58 57 AM](https://github.com/user-attachments/assets/8692190f-578e-4a9a-af4e-56b9bada1f5b)

2) plotting a "slice" works, but even if the metadata states that period increases "down", the resulting plot is still ordered from low at the bottom to high at the top. It would probably be better if this was flipped (as it is if there is a depth variable for the xsection choice), since increasing period is correlated with increasing depth.
![Figure_1](https://github.com/user-attachments/assets/145bfffa-98c3-4619-b00b-51bd0cb7b208)

Lastly, it doesn't look like github will allow the attachment of a .nc file...so we may need to reconsider how people submit their volumes

**Comment by manoch-iris** [comment]
Hi Jon,

1. Thank you for bringing this to my attention. The issue has been resolved, and I have also enhanced support for non-geospatial models in general. Please let me know if you encounter any further issues.

2. Technically, the code is functioning as intended. Since the model is not geospatial (lacking depth), the vertical geospatial direction does not apply to variables like the period. What you need to do is define the period range in the desired direction. For example, in this case, you could provide the period range as 162,18.

3. I agree that we need to reconsider the submission strategy. If they could provide a link to download their model, that would be the ideal solution.

Best,
--manoch
